# Generated by Django 3.1.3 on 2021-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='blog/images')),
                ('heading', models.CharField(max_length=70)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
