# Generated by Django 3.1.3 on 2021-01-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='img',
            new_name='image',
        ),
    ]
