# Generated by Django 3.1.3 on 2021-01-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210103_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='heading',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
